export const projectDetailsData = [
	{
		id: 1,
		slug: "ecopets",
		src: "/earth.jpg",
		title: "Ecopets - Sustainability Task Tracker",
		description:
			"This was an individual project for Backend Development module in my year 1 at SP. \n\nIt's a full-stack web application that encourages sustainable habits through gamification.\n\n Users can complete daily sustainability tasks, earn points, adopt and level up virtual pets, and participate in daily challenges. A community leaderboard promotes friendly competition and long-term engagement.",
		tabs: [
			{ id: 1, name: "JavaScript" },
			{ id: 2, name: "HTML/CSS" },
			{ id: 3, name: "Bootstrap" },
			{ id: 4, name: "Express.js" },
			{ id: 5, name: "MySQL" },
			{ id: 6, name: "Node.js" },
			{ id: 7, name: "Postman" },
			{ id: 8, name: "GitHub" },
		],
		href: "https://bed-ca2-atdt.onrender.com/",
		videoId: "amj_GAr4jbM",
	},
	{
		id: 2,
		slug: "study-group",
		src: "/study.jpg",
		title: "Study Group Web Application",
		description:
			"This was a four-person group project. It's a full-stack study group web application designed for Singapore Polytechnic students.\n\n I implemented features that allow users to create and join study groups, book on-campus study rooms, manage bookings, and submit feedback after each study session.\n\nMain learning points from this projects are version control using GitHub, state management features and collaboration with team members.",
		tabs: [
			{ id: 1, name: "JavaScript" },
			{ id: 2, name: "HTML/CSS" },
			{ id: 3, name: "Bootstrap" },
			{ id: 4, name: "Prisma ORM" },
			{ id: 5, name: "Neon Database" },
			{ id: 6, name: "GitHub" },
			{ id: 7, name: "Azure" },
		],
		href: "https://grp1-gitgud-cicd-cebtafaaa3djfwhk.southeastasia-01.azurewebsites.net/",
	},
	{
		id: 3,
		src: "/amber.png",
		slug: "amber-creative",
		title: "Amber Creative - Website Development",
		description:
			"During my internship at Amber Creative, I started learning React and Tailwind CSS. This project was one of the projects I did during internship.\n\nIt's a portfolio website developed for the company and was built using React, Tailwind CSS, Framer Motion, and Directus CMS to deliver a modern, responsive, and animated user experience.\n\n Main learning points would be attention to details in design implementation, responsive design, learning new Content Management System (CMS) and working in a professional environment.",
		tabs: [
			{ id: 1, name: "React" },
			{ id: 2, name: "TypeScript" },
			{ id: 3, name: "Tailwind CSS" },
			{ id: 4, name: "Framer Motion" },
			{ id: 5, name: "Directus CMS" },
			{ id: 6, name: "GitHub" },
		],
		href: "https://ambercreative.sg/",
	},
	{
		id: 4,
		src: "/hope-fu.png",
		slug: "hopefu",
		title: "Hopefu - Personality Test Web App",
		description:
			"I got to participate in this project with a friend's recommendation. Their project theme was something I haven't done before so I decided to volunteer in development process.\n\nIt's a personality test web application focused on self-discovery and personal growth. Users can explore their strengths, reflect through journaling features, and set personal goals to track their development over time.",
		tabs: [
			{ id: 1, name: "React" },
			{ id: 2, name: "TypeScript" },
			{ id: 3, name: "Tailwind CSS" },
			{ id: 4, name: "Supabase" },
			{ id: 5, name: "GitHub" },
			{ id: 6, name: "Google Auth" },
		],
		href: "https://hope-fu.onrender.com/",
	},
	{
		id: 5,
		src: "/v1.png",
		slug: "portfolio",
		title: "Portfolio Website Version 1",
		description:
			"This was my first ever portfolio website built using React, TypeScript, Tailwind CSS and Framer Motion.\n\n It was a learning journey as I was still getting used to these technologies back then. Building this website helped me understand the fundamentals of React components, state management, and responsive design.",
		tabs: [
			{ id: 1, name: "React" },
			{ id: 2, name: "TypeScript" },
			{ id: 3, name: "Tailwind CSS" },
			{ id: 4, name: "Framer Motion" },
			{ id: 5, name: "GitHub" },
			{ id: 6, name: "Aceternity UI" },
		],
		href: "https://by-anna.vercel.app/",
	},
	{
		id: 6,
		src: "/typing.png",
		slug: "typing-game",
		title: "Coffee Type - Typing Game",
		description:
			"I love playing typing games whenever I feel like practising my typing skills. So, I decided to develop one so that I can play it myself.\n\n It's a coffee-themed typing game that helps users improve typing speed and accuracy.\n\nBackend development is in progress to support user authentication and progress tracking.",
		tabs: [
			{ id: 1, name: "React" },
			{ id: 2, name: "TypeScript" },
			{ id: 3, name: "Tailwind CSS" },
			{ id: 4, name: "Framer Motion" },
			{ id: 5, name: "Prisma ORM" },
		],
		href: "https://coffee-type.vercel.app/",
	},
];
